### ISSUE TITLE
can someone recover ERC20 token

### ISSUE THREAD

**Issue by Speedevs** [vittominacori/erc20-generator#18]
Let me explain, how can I reverse token transfered to a fraudster is there by anyway with the token generator be able to recover Erc20 token . (With the Erc20 recover function)

**Comment by vittominacori** [comment]
No, you can't reverse transferred tokens otherwise you could steal tokens from users' wallet.
The recover ERC20 function is intended to be used if someone send tokens to your token contract for error. In that case you can recover these tokens by using the [ETH Token Recover](https://vittominacori.github.io/eth-token-recover/) behaviour included in your token.

**Comment by Speedevs** [comment]
So it means the token is gone forever I can't do anything about it

**Comment by vittominacori** [comment]
Basically yes. As in the ERC20 protocol.

**Comment by Speedevs** [comment]
Oh ok how can I do it

**Comment by vittominacori** [comment]
You can't recover stolen tokens.
Anyway paste here token address or trx hash to check.

**Comment by Speedevs** [comment]
The stolen token txnhash ; https://etherscan.io/tx/0xd6946762c1516484c5f5119bb14f161395d5c196b635991542cbf5be6fcc1055

**Comment by vittominacori** [comment]
No, I’m sorry but you can’t recover tokens. 
Do not send tokens to addresses you don’t trust.
