### ISSUE TITLE
Add EIP-2612 permit approvals

### ISSUE THREAD

**Issue by VieYang** [vittominacori/erc20-generator#31]
add EIP-2612 712-signed approvals, https://eips.ethereum.org/EIPS/eip-2612

**Comment by vittominacori** [comment]
It is a pro feature for a token to have. Most using generator are standard users. 
Anyway token implements ERC1363 which have `transferAndCall`, `approveAndCall` function in order to make a callback after a transfer or an approve.

Maybe in a future release I can consider to add EIP-2612 for a pro version of the token.

**Comment by VieYang** [comment]
`EIP-2612 permit approvals`  can allow users to transfer tokens without holding ETH, this is  very friendly to some novice users
