### ISSUE TITLE
PowerfulERC20 with no cap (or MintableERC20 with ERC1363)

### ISSUE THREAD

**Issue by 1blockologist** [vittominacori/erc20-generator#46]
Would love to be able to select features of your contracts. I can understand how it will be difficult to really automatically code variations properly.

The current issue is that the PowerfulERC20 has the cap function, when I don't necessarily want it. But the MintableERC20 is closer to what I want but does not have the features of the PowerfulERC20.

A solution would be to have a PowerfulMintERC20 feature where there is no cap. Or allow the dropdown to be changed from "capped" to "unlimited" in the PowerfulERC20 mode.

For now I allow the maximum supply to be much larger than the initial supply, and I could burn the owner keys later to prevent more minting, but it is hard to say what the future really holds.

also #45 would allow users to deploy now and use the boutique features later.

**Comment by vittominacori** [comment]
As you can understand it is not easy to customize code by enabling features. There could be many combinations to handle.
For this reason it works as reverse, so you can choose a token type and then you can see what they are the features enabled.

In your case you can choose PowerfulERC20 and set an higher upper limit. When you don't want to mint tokens anymore you can call the `finishMinting` function that will disable the mint function. Don't need to burn the owner keys because of you can use it to recover tokens sent into your contract for error.
Your holders will be able to see that minting is finished and trust you by analyzing the smart contract.
