### ISSUE TITLE
Warning! Error encountered during contract execution [Out of gas]

### ISSUE THREAD

**Issue by 4bcco** [vittominacori/erc20-generator#6]
How to know how much gas limit to put?

On the test net no problem creating contract. fail twice on the main net with tx fee of more than 9$ https://etherscan.io/tx/0xf76e3d59376f68bc1f44ff0596824b5e62ecc7e339cc0fbaef6f601f60ee5220

Is this tx fee lost forever?

**Comment by vittominacori** [comment]
Hi, I'm sorry for your unfortunate trx fee.

MetaMask should calculate the right Gas amount automatically. So don't change it.
You can set Gas Price to 1Gwei instead of 23Gwei and you should pay about **$0.5**.

Look there https://etherscan.io/tx/0x9ead876af7161f346f425d8553b666326efd11646b92a672de28e32ce8e22b23
it is a successful trx and it uses about 2,700,000 Gas. So setting a max of 3M should work.

**Comment by 4bcco** [comment]
Thanks for this info Vittorio,

My MataMask might be outdated, all I got was 1Gwei and 0 Gas
